package com.potion;

import com.google.common.collect.ImmutableMap;
import net.runelite.api.ItemID;

import java.util.Map;

public enum PotionDoseIdentification {
    SUPER_STRENGTH4(4, ItemID.SUPER_STRENGTH4), SUPER_STRENGTH3(3, ItemID.SUPER_STRENGTH3), SUPER_STRENGTH2(2, ItemID.SUPER_STRENGTH2), SUPER_STRENGTH1(1, ItemID.SUPER_STRENGTH1),


    ATTACK_POTION4(4, ItemID.ATTACK_POTION4), ATTACK_POTION3(3, ItemID.ATTACK_POTION3), ATTACK_POTION2(2, ItemID.ATTACK_POTION2), ATTACK_POTION1(1, ItemID.ATTACK_POTION1),


    RESTORE_POTION4(4, ItemID.RESTORE_POTION4), RESTORE_POTION3(3, ItemID.RESTORE_POTION3), RESTORE_POTION2(2, ItemID.RESTORE_POTION2), RESTORE_POTION1(1, ItemID.RESTORE_POTION1),


    DEFENCE_POTION4(4, ItemID.DEFENCE_POTION4), DEFENCE_POTION3(3, ItemID.DEFENCE_POTION3), DEFENCE_POTION2(2, ItemID.DEFENCE_POTION2), DEFENCE_POTION1(1, ItemID.DEFENCE_POTION1),


    PRAYER_POTION4(4, ItemID.PRAYER_POTION4), PRAYER_POTION3(3, ItemID.PRAYER_POTION3), PRAYER_POTION2(2, ItemID.PRAYER_POTION2), PRAYER_POTION1(1, ItemID.PRAYER_POTION1),


    FISHING_POTION4(4, ItemID.FISHING_POTION4), FISHING_POTION3(3, ItemID.FISHING_POTION3), FISHING_POTION2(2, ItemID.FISHING_POTION2), FISHING_POTION1(1, ItemID.FISHING_POTION1),


    RANGING_POTION4(4, ItemID.RANGING_POTION4), RANGING_POTION3(3, ItemID.RANGING_POTION3), RANGING_POTION2(2, ItemID.RANGING_POTION2), RANGING_POTION1(1, ItemID.RANGING_POTION1),


    STRENGTH_POTION4(4, ItemID.STRENGTH_POTION4), STRENGTH_POTION3(3, ItemID.STRENGTH_POTION3), STRENGTH_POTION2(2, ItemID.STRENGTH_POTION2), STRENGTH_POTION1(1, ItemID.STRENGTH_POTION1),

    ANTIFIRE_POTION4(4, ItemID.ANTIFIRE_POTION4), ANTIFIRE_POTION3(3, ItemID.ANTIFIRE_POTION3), ANTIFIRE_POTION2(2, ItemID.ANTIFIRE_POTION2), ANTIFIRE_POTION1(1, ItemID.ANTIFIRE_POTION1),


    ENERGY_POTION4(4, ItemID.ENERGY_POTION4), ENERGY_POTION3(3, ItemID.ENERGY_POTION3), ENERGY_POTION2(2, ItemID.ENERGY_POTION2), ENERGY_POTION1(1, ItemID.ENERGY_POTION1),


    AGILITY_POTION4(4, ItemID.AGILITY_POTION4), AGILITY_POTION3(3, ItemID.AGILITY_POTION3), AGILITY_POTION2(2, ItemID.AGILITY_POTION2), AGILITY_POTION1(1, ItemID.AGILITY_POTION1),

    COMPOST_POTION4(4, ItemID.COMPOST_POTION4), COMPOST_POTION3(3, ItemID.COMPOST_POTION3), COMPOST_POTION2(2, ItemID.COMPOST_POTION2), COMPOST_POTION1(1, ItemID.COMPOST_POTION1),


    MAGIC_POTION4(4, ItemID.MAGIC_POTION4), MAGIC_POTION3(3, ItemID.MAGIC_POTION3), MAGIC_POTION2(2, ItemID.MAGIC_POTION2), MAGIC_POTION1(1, ItemID.MAGIC_POTION1),


    COMBAT_POTION4(4, ItemID.COMBAT_POTION4), COMBAT_POTION3(3, ItemID.COMBAT_POTION3), COMBAT_POTION2(2, ItemID.COMBAT_POTION2), COMBAT_POTION1(1, ItemID.COMBAT_POTION1),


    HUNTER_POTION4(4, ItemID.HUNTER_POTION4), HUNTER_POTION3(3, ItemID.HUNTER_POTION3), HUNTER_POTION2(2, ItemID.HUNTER_POTION2), HUNTER_POTION1(1, ItemID.HUNTER_POTION1),


    STAMINA_POTION4(4, ItemID.STAMINA_POTION4), STAMINA_POTION3(3, ItemID.STAMINA_POTION3), STAMINA_POTION2(2, ItemID.STAMINA_POTION2), STAMINA_POTION1(1, ItemID.STAMINA_POTION1),


    SUPER_COMBAT_POTION4(4, ItemID.SUPER_COMBAT_POTION4), SUPER_COMBAT_POTION3(3, ItemID.SUPER_COMBAT_POTION3), SUPER_COMBAT_POTION2(2, ItemID.SUPER_COMBAT_POTION2), SUPER_COMBAT_POTION1(1, ItemID.SUPER_COMBAT_POTION1),


    BASTION_POTION4(4, ItemID.BASTION_POTION4), BASTION_POTION3(3, ItemID.BASTION_POTION3), BASTION_POTION2(2, ItemID.BASTION_POTION2), BASTION_POTION1(1, ItemID.BASTION_POTION1),


    BATTLEMAGE_POTION4(4, ItemID.BATTLEMAGE_POTION4), BATTLEMAGE_POTION3(3, ItemID.BATTLEMAGE_POTION3), BATTLEMAGE_POTION2(2, ItemID.BATTLEMAGE_POTION2), BATTLEMAGE_POTION1(1, ItemID.BATTLEMAGE_POTION1),


    DIVINE_BASTION_POTION4(4, ItemID.DIVINE_BASTION_POTION4), DIVINE_BASTION_POTION3(3, ItemID.DIVINE_BASTION_POTION3), DIVINE_BASTION_POTION2(2, ItemID.DIVINE_BASTION_POTION2), DIVINE_BASTION_POTION1(1, ItemID.DIVINE_BASTION_POTION1),


    DIVINE_BATTLEMAGE_POTION4(4, ItemID.DIVINE_BATTLEMAGE_POTION4), DIVINE_BATTLEMAGE_POTION3(3, ItemID.DIVINE_BATTLEMAGE_POTION3), DIVINE_BATTLEMAGE_POTION2(2, ItemID.DIVINE_BATTLEMAGE_POTION2), DIVINE_BATTLEMAGE_POTION1(1, ItemID.DIVINE_BATTLEMAGE_POTION1),


    DIVINE_MAGIC_POTION4(4, ItemID.DIVINE_MAGIC_POTION4), DIVINE_MAGIC_POTION3(3, ItemID.DIVINE_MAGIC_POTION3), DIVINE_MAGIC_POTION2(2, ItemID.DIVINE_MAGIC_POTION2), DIVINE_MAGIC_POTION1(1, ItemID.DIVINE_MAGIC_POTION1),


    DIVINE_RANGING_POTION4(4, ItemID.DIVINE_RANGING_POTION4), DIVINE_RANGING_POTION3(3, ItemID.DIVINE_RANGING_POTION3), DIVINE_RANGING_POTION2(2, ItemID.DIVINE_RANGING_POTION2), DIVINE_RANGING_POTION1(1, ItemID.DIVINE_RANGING_POTION1),


    DIVINE_SUPER_ATTACK_POTION4(4, ItemID.DIVINE_SUPER_ATTACK_POTION4), DIVINE_SUPER_ATTACK_POTION3(3, ItemID.DIVINE_SUPER_ATTACK_POTION3), DIVINE_SUPER_ATTACK_POTION2(2, ItemID.DIVINE_SUPER_ATTACK_POTION2), DIVINE_SUPER_ATTACK_POTION1(1, ItemID.DIVINE_SUPER_ATTACK_POTION1),


    DIVINE_SUPER_COMBAT_POTION4(4, ItemID.DIVINE_SUPER_COMBAT_POTION4), DIVINE_SUPER_COMBAT_POTION3(3, ItemID.DIVINE_SUPER_COMBAT_POTION3), DIVINE_SUPER_COMBAT_POTION2(2, ItemID.DIVINE_SUPER_COMBAT_POTION2), DIVINE_SUPER_COMBAT_POTION1(1, ItemID.DIVINE_SUPER_COMBAT_POTION1),


    DIVINE_SUPER_DEFENCE_POTION4(4, ItemID.DIVINE_SUPER_DEFENCE_POTION4), DIVINE_SUPER_DEFENCE_POTION3(3, ItemID.DIVINE_SUPER_DEFENCE_POTION3), DIVINE_SUPER_DEFENCE_POTION2(2, ItemID.DIVINE_SUPER_DEFENCE_POTION2), DIVINE_SUPER_DEFENCE_POTION1(1, ItemID.DIVINE_SUPER_DEFENCE_POTION1),


    DIVINE_SUPER_STRENGTH_POTION4(4, ItemID.DIVINE_SUPER_STRENGTH_POTION4), DIVINE_SUPER_STRENGTH_POTION3(3, ItemID.DIVINE_SUPER_STRENGTH_POTION3), DIVINE_SUPER_STRENGTH_POTION2(2, ItemID.DIVINE_SUPER_STRENGTH_POTION2), DIVINE_SUPER_STRENGTH_POTION1(1, ItemID.DIVINE_SUPER_STRENGTH_POTION1),


    SUPER_ANTIFIRE_POTION4(4, ItemID.SUPER_ANTIFIRE_POTION4), SUPER_ANTIFIRE_POTION3(3, ItemID.SUPER_ANTIFIRE_POTION3), SUPER_ANTIFIRE_POTION2(2, ItemID.SUPER_ANTIFIRE_POTION2), SUPER_ANTIFIRE_POTION1(1, ItemID.SUPER_ANTIFIRE_POTION1),


    ABSORPTION_4(4, ItemID.ABSORPTION_4), ABSORPTION_3(3, ItemID.ABSORPTION_3), ABSORPTION_2(2, ItemID.ABSORPTION_2), ABSORPTION_1(1, ItemID.ABSORPTION_1),

    OVERLOAD_4(4, ItemID.OVERLOAD_4), OVERLOAD_3(3, ItemID.OVERLOAD_3), OVERLOAD_2(2, ItemID.OVERLOAD_2), OVERLOAD_1(1, ItemID.OVERLOAD_1),

    ANTIVENOM4(4, ItemID.ANTIVENOM4), ANTIVENOM3(3, ItemID.ANTIVENOM3), ANTIVENOM2(2, ItemID.ANTIVENOM2), ANTIVENOM1(1, ItemID.ANTIVENOM1),

    ANTIVENOM_PLUS_4(4, ItemID.ANTIVENOM4_12913), ANTIVENOM_PLUS_3(3, ItemID.ANTIVENOM3_12915), ANTIVENOM_PLUS_2(2, ItemID.ANTIVENOM2_12917), ANTIVENOM_PLUS_1(1, ItemID.ANTIVENOM1_12919),

    ANTIDOTE_PLUS_4(4, ItemID.ANTIDOTE4), ANTIDOTE_PLUS_3(3, ItemID.ANTIDOTE3), ANTIDOTE_PLUS_2(2, ItemID.ANTIDOTE2), ANTIDOTE_PLUS_1(1, ItemID.ANTIDOTE1),

    ANTIDOTE_PLUS_PLUS_4(4, ItemID.ANTIDOTE4_5952), ANTIDOTE_PLUS_PLUS_3(3, ItemID.ANTIDOTE3_5954), ANTIDOTE_PLUS_PLUS_2(2, ItemID.ANTIDOTE2_5956), ANTIDOTE_PLUS_PLUS_1(1, ItemID.ANTIDOTE1_5958),

    ANTIPOISON4(4, ItemID.ANTIPOISON4), ANTIPOISON3(3, ItemID.ANTIPOISON3), ANTIPOISON2(2, ItemID.ANTIPOISON2), ANTIPOISON1(1, ItemID.ANTIPOISON1),

    BLIGHTED_SUPER_RESTORE4(4, ItemID.BLIGHTED_SUPER_RESTORE4), BLIGHTED_SUPER_RESTORE3(3, ItemID.BLIGHTED_SUPER_RESTORE3), BLIGHTED_SUPER_RESTORE2(2, ItemID.BLIGHTED_SUPER_RESTORE2), BLIGHTED_SUPER_RESTORE1(1, ItemID.BLIGHTED_SUPER_RESTORE1),

    SANFEW_SERUM4(4, ItemID.SANFEW_SERUM4), SANFEW_SERUM3(3, ItemID.SANFEW_SERUM3), SANFEW_SERUM2(2, ItemID.SANFEW_SERUM2), SANFEW_SERUM1(1, ItemID.SANFEW_SERUM1),

    SARADOMIN_BREW4(4, ItemID.SARADOMIN_BREW4), SARADOMIN_BREW3(3, ItemID.SARADOMIN_BREW3), SARADOMIN_BREW2(2, ItemID.SARADOMIN_BREW2), SARADOMIN_BREW1(1, ItemID.SARADOMIN_BREW1),

    SUPERANTIPOISON4(4, ItemID.SUPERANTIPOISON4), SUPERANTIPOISON3(3, ItemID.SUPERANTIPOISON3), SUPERANTIPOISON2(2, ItemID.SUPERANTIPOISON2), SUPERANTIPOISON1(1, ItemID.SUPERANTIPOISON1),

    ZAMORAK_BREW4(4, ItemID.ZAMORAK_BREW4), ZAMORAK_BREW3(3, ItemID.ZAMORAK_BREW3), ZAMORAK_BREW2(2, ItemID.ZAMORAK_BREW2), ZAMORAK_BREW1(1, ItemID.ZAMORAK_BREW1),

    EXTENDED_SUPER_ANTIFIRE4(4, ItemID.EXTENDED_SUPER_ANTIFIRE4), EXTENDED_SUPER_ANTIFIRE3(3, ItemID.EXTENDED_SUPER_ANTIFIRE3), EXTENDED_SUPER_ANTIFIRE2(2, ItemID.EXTENDED_SUPER_ANTIFIRE2), EXTENDED_SUPER_ANTIFIRE1(1, ItemID.EXTENDED_SUPER_ANTIFIRE1),

    EXTENDED_ANTIFIRE4(4, ItemID.EXTENDED_ANTIFIRE4), EXTENDED_ANTIFIRE3(3, ItemID.EXTENDED_ANTIFIRE3), EXTENDED_ANTIFIRE2(2, ItemID.EXTENDED_ANTIFIRE2), EXTENDED_ANTIFIRE1(1, ItemID.EXTENDED_ANTIFIRE1),

    FORGOTTEN_BREW4(4, ItemID.FORGOTTEN_BREW4), FORGOTTEN_BREW3(3, ItemID.FORGOTTEN_BREW3), FORGOTTEN_BREW2(2, ItemID.FORGOTTEN_BREW2), FORGOTTEN_BREW1(1, ItemID.FORGOTTEN_BREW1),

    ;

    private static final Map<Integer, PotionDoseIdentification> potionDoseIdentifications;

    static {
        ImmutableMap.Builder<Integer, PotionDoseIdentification> builder = new ImmutableMap.Builder<>();

        for (PotionDoseIdentification i : values()) {
            for (int id : i.itemIDs) {
                builder.put(id, i);
            }
        }

        potionDoseIdentifications = builder.build();
    }

    final int[] itemIDs;
    final int count;

    PotionDoseIdentification(int count, int... ids) {
        this.count = count;
        this.itemIDs = ids;
    }

    static PotionDoseIdentification get(int id) {
        return potionDoseIdentifications.get(id);
    }
}
